// Famous bakeries to discover, by city. Read-only reference data.
// Each entry is just { name, area } — enough to open a keyless Google Maps
// search (see lib/maps.js) and to add to your "Want to try" list.
//
// ⚠️ CURATED FROM PUBLIC "best bakery" LISTS + GOOGLE MAPS — names and
// neighborhoods should be spot-checked by Sara before treating as canonical.
// Princeton is the home turf (starts at 10); the rest start at ~15–20 each and
// can grow to 30/city later.

export const SEED_CITIES = [
  {
    city: 'Princeton, NJ',
    bakeries: [
      { name: 'Terra Momo Bread Company', area: 'Witherspoon St' },
      { name: 'Olives', area: 'Witherspoon St' },
      { name: 'The Bent Spoon', area: 'Palmer Square' },
      { name: 'Small World Coffee', area: 'Witherspoon St' },
      { name: 'Jammin’ Crepes', area: 'Nassau St' },
      { name: 'Chez Alice Café & Bakery', area: 'Palmer Square' },
      { name: 'House of Cupcakes', area: 'Nassau St' },
      { name: 'Bon Appétit Fine Foods', area: 'Palmer Square' },
      { name: 'Main Street Bistro & Bakery', area: 'Kingston, NJ' },
      { name: 'Boro Bean', area: 'Hopewell, NJ' },
    ],
  },
  {
    city: 'New York City',
    bakeries: [
      { name: 'Levain Bakery', area: 'Upper West Side' },
      { name: 'Dominique Ansel Bakery', area: 'SoHo' },
      { name: 'Balthazar Bakery', area: 'SoHo' },
      { name: 'Breads Bakery', area: 'Union Square' },
      { name: 'Sullivan Street Bakery', area: 'Hell’s Kitchen' },
      { name: 'Ess-a-Bagel', area: 'Midtown East' },
      { name: 'Russ & Daughters', area: 'Lower East Side' },
      { name: 'Magnolia Bakery', area: 'West Village' },
      { name: 'Bouchon Bakery', area: 'Columbus Circle' },
      { name: 'Maman', area: 'SoHo' },
      { name: 'L’Appartement 4F', area: 'Brooklyn Heights' },
      { name: 'She Wolf Bakery', area: 'Brooklyn' },
      { name: 'Peter Pan Donut & Pastry', area: 'Greenpoint' },
      { name: 'Bien Cuit', area: 'Boerum Hill, Brooklyn' },
      { name: 'Orwashers Bakery', area: 'Upper East Side' },
      { name: 'Lafayette Grand Café & Bakery', area: 'NoHo' },
      { name: 'Fabrique Bakery', area: 'NoMad' },
      { name: 'Radio Bakery', area: 'Greenpoint' },
    ],
  },
  {
    city: 'Chicago',
    bakeries: [
      { name: 'Lost Larson', area: 'Andersonville' },
      { name: 'Publican Quality Bread', area: 'West Loop' },
      { name: 'Floriole Café & Bakery', area: 'Lincoln Park' },
      { name: 'Bang Bang Pie & Biscuits', area: 'Logan Square' },
      { name: 'Sweet Mandy B’s', area: 'Lincoln Park' },
      { name: 'Vanille Patisserie', area: 'Lincoln Park' },
      { name: 'La Fournette', area: 'Old Town' },
      { name: 'Hendrickx Belgian Bread Crafter', area: 'Gold Coast' },
      { name: 'Baker Miller', area: 'Lincoln Square' },
      { name: 'Middle East Bakery & Grocery', area: 'Andersonville' },
      { name: 'Roeser’s Bakery', area: 'Humboldt Park' },
      { name: 'Pierrot Gourmet', area: 'River North' },
      { name: 'Bombobar', area: 'River North' },
      { name: 'Cellar Door Provisions', area: 'Logan Square' },
      { name: 'Beurrage Bakehouse', area: 'West Town' },
    ],
  },
  {
    city: 'Los Angeles',
    bakeries: [
      { name: 'République', area: 'Mid-City' },
      { name: 'Bub and Grandma’s', area: 'Glassell Park' },
      { name: 'Clark Street Bakery', area: 'Grand Central Market' },
      { name: 'Gjusta', area: 'Venice' },
      { name: 'Bottega Louie', area: 'Downtown' },
      { name: 'Proof Bakery', area: 'Atwater Village' },
      { name: 'Lodge Bread Co.', area: 'Culver City' },
      { name: 'Sqirl', area: 'Silver Lake' },
      { name: 'La Monarca Bakery', area: 'Santa Monica' },
      { name: 'Cake Monkey Bakery', area: 'Fairfax' },
      { name: 'Maury’s Bagels', area: 'Silver Lake' },
      { name: 'Superba Food + Bread', area: 'Venice' },
      { name: 'Tartine', area: 'Downtown (Manufactory)' },
      { name: 'Bakers Bench', area: 'Chinatown' },
      { name: 'Frog Hollow / Semi Sweet Bakery', area: 'Downtown' },
    ],
  },
  {
    city: 'San Francisco',
    bakeries: [
      { name: 'Tartine Bakery', area: 'Mission' },
      { name: 'Tartine Manufactory', area: 'Mission' },
      { name: 'Arsicault Bakery', area: 'Richmond' },
      { name: 'b. patisserie', area: 'Lower Pacific Heights' },
      { name: 'Boudin Bakery', area: 'Fisherman’s Wharf' },
      { name: 'Craftsman and Wolves', area: 'Mission' },
      { name: 'Neighbor Bakehouse', area: 'Dogpatch' },
      { name: 'Acme Bread', area: 'Ferry Building' },
      { name: 'Le Marais Bakery', area: 'Marina' },
      { name: 'Devil’s Teeth Baking Company', area: 'Outer Sunset' },
      { name: 'Mr. Holmes Bakehouse', area: 'Tenderloin' },
      { name: 'Thorough Bread and Pastry', area: 'Castro' },
      { name: 'The Mill', area: 'NoPa' },
      { name: 'Noe Valley Bakery', area: 'Noe Valley' },
      { name: 'Jane the Bakery', area: 'Lower Nob Hill' },
    ],
  },
  {
    city: 'Paris',
    bakeries: [
      { name: 'Du Pain et des Idées', area: '10e' },
      { name: 'Poilâne', area: '6e' },
      { name: 'Cédric Grolet Opéra', area: '2e' },
      { name: 'Boulangerie Utopie', area: '11e' },
      { name: 'Mamiche', area: '9e' },
      { name: 'Pierre Hermé', area: '6e' },
      { name: 'Maison Landemaine', area: 'Montmartre' },
      { name: 'Le Grenier à Pain', area: 'Montmartre' },
      { name: 'Blé Sucré', area: '12e' },
      { name: 'La Maison d’Isabelle', area: '5e' },
      { name: 'Circus Bakery', area: '6e' },
      { name: 'BO&MIE', area: '1er' },
      { name: 'Liberté', area: '10e' },
      { name: 'Stohrer', area: '2e' },
      { name: 'Des Gâteaux et du Pain', area: '15e' },
      { name: 'Mokonuts', area: '11e' },
      { name: 'Ten Belles Bread', area: '11e' },
      { name: 'Land&Monkeys', area: 'Le Marais' },
    ],
  },
  {
    city: 'Seoul',
    bakeries: [
      { name: 'Nudake', area: 'Seongsu' },
      { name: 'Onion', area: 'Anguk' },
      { name: 'London Bagel Museum', area: 'Anguk' },
      { name: 'Layered', area: 'Yeonnam-dong' },
      { name: 'OUR Bakery', area: 'Apgujeong' },
      { name: 'Publique', area: 'Haebangchon' },
      { name: 'Tartine', area: 'Itaewon' },
      { name: 'Le Alaska', area: 'Yeonnam-dong' },
      { name: 'Peter Pan 1978', area: 'Bangbae' },
      { name: 'Sungsimdang', area: 'Daejeon (flagship)' },
      { name: 'Millac Bakery', area: 'Seongsu' },
      { name: 'Coffee Nap Roasters', area: 'Yangjae' },
      { name: 'Café Onion Gwangjang', area: 'Jongno' },
      { name: 'Bread05', area: 'Seongsu' },
      { name: 'Artisan Bakers', area: 'Hannam-dong' },
    ],
  },
]
