// Famous bakeries to discover, by city. Read-only reference data.
// Each entry is { name, area } plus, for the well-known ones, an optional
// `photo` (a stable Wikimedia Commons image) and exact `lat`/`lng`. These ride
// through the log flow so ranking one from Discover auto-fills its photo + map
// pin — no manual photo, no geocode round-trip. The rest keep the emoji fallback.
//
// ⚠️ CURATED FROM PUBLIC "best bakery" LISTS + GOOGLE MAPS — names and
// neighborhoods should be spot-checked by Sara before treating as canonical.
// Princeton is the home turf (starts at 10); the rest start at ~15–20 each and
// can grow to 30/city later.

export const SEED_CITIES = [
  {
    city: 'Princeton, NJ',
    bakeries: [
      { name: 'Terra Momo Bread Company', area: 'Witherspoon St' },
      { name: 'Olives', area: 'Witherspoon St' },
      { name: 'The Bent Spoon', area: 'Palmer Square' },
      { name: 'Small World Coffee', area: 'Witherspoon St' },
      { name: 'Jammin’ Crepes', area: 'Nassau St' },
      { name: 'Chez Alice Café & Bakery', area: 'Palmer Square' },
      { name: 'House of Cupcakes', area: 'Nassau St' },
      { name: 'Bon Appétit Fine Foods', area: 'Palmer Square' },
      { name: 'Main Street Bistro & Bakery', area: 'Kingston, NJ' },
      { name: 'Boro Bean', area: 'Hopewell, NJ' },
    ],
  },
  {
    city: 'New York City',
    bakeries: [
      { name: 'Levain Bakery', area: 'Upper West Side', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Storefrontny.jpg?width=1024' },
      { name: 'Dominique Ansel Bakery', area: 'SoHo' },
      { name: 'Balthazar Bakery', area: 'SoHo', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Balthazar_on_Spring_Street.jpg?width=1024', lat: 40.722712, lng: -73.998159 },
      { name: 'Breads Bakery', area: 'Union Square' },
      { name: 'Sullivan Street Bakery', area: 'Hell’s Kitchen' },
      { name: 'Ess-a-Bagel', area: 'Midtown East' },
      { name: 'Russ & Daughters', area: 'Lower East Side', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Russ_%26_Daughters_%2851624125108%29.jpg?width=1024', lat: 40.72259, lng: -73.98832 },
      { name: 'Magnolia Bakery', area: 'West Village', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Magnolia_Bakery%2C_401_Bleecker_Street%2C_New_York%2C_NY_10014%2C_USA_-_Jan_2013_O.jpg?width=1024', lat: 40.7359, lng: -74.005 },
      { name: 'Bouchon Bakery', area: 'Columbus Circle' },
      { name: 'Maman', area: 'SoHo' },
      { name: 'L’Appartement 4F', area: 'Brooklyn Heights' },
      { name: 'She Wolf Bakery', area: 'Brooklyn' },
      { name: 'Peter Pan Donut & Pastry', area: 'Greenpoint' },
      { name: 'Bien Cuit', area: 'Boerum Hill, Brooklyn' },
      { name: 'Orwashers Bakery', area: 'Upper East Side' },
      { name: 'Lafayette Grand Café & Bakery', area: 'NoHo' },
      { name: 'Fabrique Bakery', area: 'NoMad' },
      { name: 'Radio Bakery', area: 'Greenpoint' },
    ],
  },
  {
    city: 'Chicago',
    bakeries: [
      { name: 'Lost Larson', area: 'Andersonville' },
      { name: 'Publican Quality Bread', area: 'West Loop' },
      { name: 'Floriole Café & Bakery', area: 'Lincoln Park' },
      { name: 'Bang Bang Pie & Biscuits', area: 'Logan Square' },
      { name: 'Sweet Mandy B’s', area: 'Lincoln Park' },
      { name: 'Vanille Patisserie', area: 'Lincoln Park' },
      { name: 'La Fournette', area: 'Old Town' },
      { name: 'Hendrickx Belgian Bread Crafter', area: 'Gold Coast' },
      { name: 'Baker Miller', area: 'Lincoln Square' },
      { name: 'Middle East Bakery & Grocery', area: 'Andersonville' },
      { name: 'Roeser’s Bakery', area: 'Humboldt Park' },
      { name: 'Pierrot Gourmet', area: 'River North' },
      { name: 'Bombobar', area: 'River North' },
      { name: 'Cellar Door Provisions', area: 'Logan Square' },
      { name: 'Beurrage Bakehouse', area: 'West Town' },
    ],
  },
  {
    city: 'Los Angeles',
    bakeries: [
      { name: 'République', area: 'Mid-City' },
      { name: 'Bub and Grandma’s', area: 'Glassell Park' },
      { name: 'Clark Street Bakery', area: 'Grand Central Market' },
      { name: 'Gjusta', area: 'Venice' },
      { name: 'Bottega Louie', area: 'Downtown', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/BottegaLouieExterior_2009-04-12.jpg?width=1024' },
      { name: 'Proof Bakery', area: 'Atwater Village' },
      { name: 'Lodge Bread Co.', area: 'Culver City' },
      { name: 'Sqirl', area: 'Silver Lake' },
      { name: 'La Monarca Bakery', area: 'Santa Monica' },
      { name: 'Cake Monkey Bakery', area: 'Fairfax' },
      { name: 'Maury’s Bagels', area: 'Silver Lake' },
      { name: 'Superba Food + Bread', area: 'Venice' },
      { name: 'Tartine', area: 'Downtown (Manufactory)' },
      { name: 'Bakers Bench', area: 'Chinatown' },
      { name: 'Frog Hollow / Semi Sweet Bakery', area: 'Downtown' },
    ],
  },
  {
    city: 'San Francisco',
    bakeries: [
      { name: 'Tartine Bakery', area: 'Mission', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tartine_bakery_exterior_in_2006.jpg?width=1024', lat: 37.761656, lng: -122.423681 },
      { name: 'Tartine Manufactory', area: 'Mission' },
      { name: 'Arsicault Bakery', area: 'Richmond' },
      { name: 'b. patisserie', area: 'Lower Pacific Heights' },
      { name: 'Boudin Bakery', area: 'Fisherman’s Wharf', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bread_in_Boudin.jpg?width=1024' },
      { name: 'Craftsman and Wolves', area: 'Mission' },
      { name: 'Neighbor Bakehouse', area: 'Dogpatch' },
      { name: 'Acme Bread', area: 'Ferry Building', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Acme_Bread_Shop_Front_2010.JPG?width=1024' },
      { name: 'Le Marais Bakery', area: 'Marina' },
      { name: 'Devil’s Teeth Baking Company', area: 'Outer Sunset' },
      { name: 'Mr. Holmes Bakehouse', area: 'Tenderloin' },
      { name: 'Thorough Bread and Pastry', area: 'Castro' },
      { name: 'The Mill', area: 'NoPa' },
      { name: 'Noe Valley Bakery', area: 'Noe Valley' },
      { name: 'Jane the Bakery', area: 'Lower Nob Hill' },
    ],
  },
  {
    city: 'Paris',
    bakeries: [
      { name: 'Du Pain et des Idées', area: '10e' },
      { name: 'Poilâne', area: '6e', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pain_Po%C3%AElane-_Paris_15e.jpg?width=1024' },
      { name: 'Cédric Grolet Opéra', area: '2e' },
      { name: 'Boulangerie Utopie', area: '11e' },
      { name: 'Mamiche', area: '9e' },
      { name: 'Pierre Hermé', area: '6e' },
      { name: 'Maison Landemaine', area: 'Montmartre' },
      { name: 'Le Grenier à Pain', area: 'Montmartre' },
      { name: 'Blé Sucré', area: '12e' },
      { name: 'La Maison d’Isabelle', area: '5e' },
      { name: 'Circus Bakery', area: '6e' },
      { name: 'BO&MIE', area: '1er' },
      { name: 'Liberté', area: '10e' },
      { name: 'Stohrer', area: '2e', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Patisserie_Stohrer_%28Paris%29.jpg?width=1024' },
      { name: 'Des Gâteaux et du Pain', area: '15e' },
      { name: 'Mokonuts', area: '11e' },
      { name: 'Ten Belles Bread', area: '11e' },
      { name: 'Land&Monkeys', area: 'Le Marais' },
    ],
  },
  {
    city: 'Seoul',
    bakeries: [
      { name: 'Nudake', area: 'Seongsu' },
      { name: 'Onion', area: 'Anguk' },
      { name: 'London Bagel Museum', area: 'Anguk' },
      { name: 'Layered', area: 'Yeonnam-dong' },
      { name: 'OUR Bakery', area: 'Apgujeong' },
      { name: 'Publique', area: 'Haebangchon' },
      { name: 'Tartine', area: 'Itaewon' },
      { name: 'Le Alaska', area: 'Yeonnam-dong' },
      { name: 'Peter Pan 1978', area: 'Bangbae' },
      { name: 'Sungsimdang', area: 'Daejeon (flagship)', photo: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sungsimdang_2019.jpg?width=1024' },
      { name: 'Millac Bakery', area: 'Seongsu' },
      { name: 'Coffee Nap Roasters', area: 'Yangjae' },
      { name: 'Café Onion Gwangjang', area: 'Jongno' },
      { name: 'Bread05', area: 'Seongsu' },
      { name: 'Artisan Bakers', area: 'Hannam-dong' },
    ],
  },
]
